---
title: "Programa del curso"
editor: 
  markdown: 
    wrap: 72
---

Este es al programa para el semester.

-   Quiero mantenerme flexible en cuanto al programa del curso para
    poder adaptarlo a las necesidades de la clase. Por lo tanto, el
    siguiente programa está sujeto a cambios, aunque sirve de guía para
    el curso.

El semestre se divide en tres partes:

-   Introducción a la morfología y las unidades de analysis: analizar la
    estructura interna de las palabras; la estuctura de las palabras (su
    sintaxis) - *Semanas 1-4*

-   Las teorías sobre la morfología - *Semanas 5-6*

-   La morfología más extendida – Lecturas - *Semanas 7 - final*

+----------------+------------------------+------------------------+
| **Semana**     | **Martes**             | **Jueves**             |
+================+========================+========================+
| Semana 1       | August 27\             | 29\                    |
|                | Introducción al curso  | Las unidades del       |
|                |                        | análisis morfológico   |
|                | -   Fábregas (2013):   |                        |
|                |     17-27              | -   Fabregas (2013):   |
|                |                        |     35-46              |
|                |                        |                        |
|                |                        | -   Pena (1999):       |
|                |                        |     4312-4318          |
+----------------+------------------------+------------------------+
| Semana 2       | September 3\           | 5\                     |
|                | La alomorfía y el      | Las estradas léxicas,  |
|                | análisis morfológico   | la flexión nominal y\  |
|                |                        | la flexión verbal      |
|                | -   Fábregas (2013):   |                        |
|                |     47-51              | -   Fábregas (2013):   |
|                |                        |     64-69              |
|                | -   Pena 1999:         |                        |
|                |     4346-4358          | -   Hualde et al.      |
|                |                        |     2010: 137-149      |
|                |                        |                        |
|                |                        | **Ejercicio 1**        |
+----------------+------------------------+------------------------+
| Semana 3       | 10\                    | 12\                    |
|                | Los verbos irregulares | La derivación, la      |
|                | y el grado de los      | composición y otros    |
|                | adjectivos y la        | procesos morfológicos  |
|                | derivación (la         | y limitaciones del     |
|                | nominalización)        | análisis morfológico   |
|                |                        |                        |
|                | -   Hualde et al.      | -   Hualde et al.      |
|                |     (2010): 150-155,   |     (2010): 178-196    |
|                |     163-178            |                        |
|                |                        | -   Pena (1999):       |
|                |                        |     4358-4364          |
+----------------+------------------------+------------------------+
| Semana 4       | 17\                    | 19\                    |
|                | La estructura interna  | La noción de "palabra" |
|                | de la palabra          | y el lugar de la       |
|                |                        | morfología             |
|                | -   Fábregas (2013):   |                        |
|                |     73-105             | -   Pena (1999):       |
|                |                        |     4327-4329          |
|                |                        |                        |
|                |                        | -   Fábregas (2013):   |
|                |                        |     51-54              |
|                |                        |                        |
|                |                        | -   Fábregas (2013):   |
|                |                        |     27-31              |
|                |                        |                        |
|                |                        | **Ejercicio 2**        |
+----------------+------------------------+------------------------+
| Semana 5       | 24\                    | 26\                    |
|                | Morfofonología y       | La flexión y su        |
|                | morfosintaxis          | análisis               |
|                |                        |                        |
|                | -   Fábregas (2013):   | -   Fábregas (2013):   |
|                |     109-143            |     175-209            |
+----------------+------------------------+------------------------+
| Semana 6       | October 1\             | 3\                     |
|                | La derivación y su     | La composición y su    |
|                | análisis               | análisis               |
|                |                        |                        |
|                | -   Fábregas (2013):   | -   Fábregas (2013):   |
|                |     211-244            |     247-276            |
|                |                        |                        |
|                |                        | **Ejercicio 3**        |
+----------------+------------------------+------------------------+
| Semana 7       | 8\                     | 10\                    |
|                | Fábregas & Gallegos    | Fábregas & Gallegos    |
|                | (2014)                 | (2014)                 |
|                |                        |                        |
|                | -   Rodrigo            | -   Rodrigo            |
+----------------+------------------------+------------------------+
| Semana 8       | 15                     | 17                     |
|                |                        |                        |
|                | -   Gutiérrez-Rexach,  | -   Navarro, Í., &     |
|                |     J., & Sessarego,   |     Espinal, M. T.     |
|                |                        |     (2012)             |
|                |     S.                 |                        |
|                |                        | **Variation**          |
|                |     <!-- -->           |                        |
|                |                        | \                      |
|                |     (2014)             | **Ejercicio 4**        |
|                |                        |                        |
|                | **Variation**          |                        |
+----------------+------------------------+------------------------+
| Semana 9       | 22                     | 24                     |
|                |                        |                        |
|                | -   Clahsen, H.,       | -   Mariscal, S.       |
|                |     Aveledo, F., &     |                        |
|                |     Roca, I. (2002)    |     (2009)             |
|                |     -   Franco         |                        |
|                |                        |     -   Kamila         |
|                | **Child acquisition**  |                        |
|                |                        | **Child acquisition**  |
+----------------+------------------------+------------------------+
| Semana 10      | 29                     | 31                     |
|                |                        |                        |
|                | -   Barnes, S. (2012). | -   Montrul, S. (2010) |
|                |                        |                        |
|                |     -   Alonso         | -   Edwin              |
|                |                        |                        |
|                |                        | **Ejercicio 5**        |
+----------------+------------------------+------------------------+
| Semana 11      | November 5             | 7                      |
|                |                        |                        |
|                | -   Scontras, G.,      | -   Domínguez, L.,     |
|                |     Polinsky, M., &    |     Arche, M. J., &    |
|                |     Fuchs, Z. (2018)   |     Myles, F. (2017)   |
|                |     -   Brenda         |     -   Ella           |
|                |                        | -   López, L. (forth)  |
|                |                        |     -   Jaylene        |
+----------------+------------------------+------------------------+
| Semana 12      | 12                     | 14                     |
|                |                        |                        |
|                | -   López, L. (2020)   | -   Project            |
|                |     -   Micah          |     presentations      |
|                |     -   Izaro          |     -   Student 1      |
|                |                        |     -   Student 2      |
|                |                        |     -   Student 3      |
|                |                        |                        |
|                |                        | **Ejercicio 6**        |
+----------------+------------------------+------------------------+
| Semana 13      | 19                     | 21                     |
|                |                        |                        |
|                | -   Project            | -   Project            |
|                |     presentations      |     presentations      |
|                |     -   Student 4      |     -   Student 7      |
|                |     -   Student 5      |     -   Student 8      |
|                |     -   Student 6      |     -   Student 9      |
+----------------+------------------------+------------------------+
| **Fall break** | **Fall break**         | **Fall break**         |
+----------------+------------------------+------------------------+
| Semana 14      | December 3\            | 5\                     |
|                | **Conferencia - No hay | **Conferencia - No hay |
|                | clase**                | clase**                |
+----------------+------------------------+------------------------+
| Semana 15      | 10\                    | 12\                    |
|                |                        | **Reading day** (no    |
|                |                        | hay clase)             |
+----------------+------------------------+------------------------+
