project:
  type: website
  output-dir: docs

website:
  title: "Morphology"
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Syllabus"
        href: span431_syllabus.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



