project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - span431_syllabus.qmd
      - 431calendar.qmd
      - Fabregas2013.qmd
      
  sidebar: 
    - title: "Semanas"
      style: "docked"
      background: light
      contents:
        - semana8.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



