project:
  type: website
  output-dir: docs

website:
  title: "Spanish Morphology"
  sidebar:
    style: "docked"
    contents: 
      - text: "Home"
        href: index.qmd
      - section: "Syllabus"
        contents:
        - span431_syllabus.qmd
        - 431calendar.qmd
      - section: "Textbooks"
        contents:
        - Fabregas2013.qmd
        - bd1999.qmd
      - section: "Articles"
        contents: 
        - articles.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



