project:
  type: website
  output-dir: docs

website:
  title: "Spanish Morphology"
  sidebar:
    style: "docked"
    contents: 
      - text: "Home"
        href: index.qmd
      - section: "Syllabus"
        contents:
        - span431_syllabus.qmd
        - 431calendar.qmd
      - section: "Textbooks"
        contents:
        - Fabregas2013.qmd
        - bd1999.qmd
        - hualde2010.qmd
      - section: "Articles"
        contents: 
        - articles.qmd
      - section: "Semana 1"
        contents:
        - semana1.qmd
      - section: "Semana 2"
        contents: 
        - w1d2.qmd
        - handout3.qmd
        - handout4.qmd
      - section: "Semana 3"
        contents:
        - handout5.qmd
        - laderivacion.qmd
      - section: "Semana 4"
        contents: 
        - handout9.qmd
        - handout10.qmd
      - section: "Semana 5"
        contents: 
        - handou11.qmd
        - handout12.qmd
      - section: "Semana 6"
        contents: 
        - handout13.qmd
      - section: "Semana 7"
        contents: 
        - fabregas_gallegos_2014.qmd
      - section: "Semana 8"
        contents: 
        - gutierrezrexach_sessarego_2014.qmd
        - navarro_espinal_2012.qmd
      - section: "Semana 9"
        contents: 
        - clahsen_roca_2002.qmd
        - mariscal_2009.qmd
      - section: "Semana 10"
        contents:
        - barnes.qmd
        - montrul.qmd
      - section: "Semana 11"
        contents:
        - scontras.qmd
        - dominguez.qmd
        - lopez.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



