project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd 
      - span431_syllabus.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



