project:
  type: website
  output-dir: docs

website:
  title: "Morphology"
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Syllabus"
        contents: 
        - span431_syllabus.qmd
        - 431calendar.qmd
      - section: "Semanas"
        contents: 
        - semana1.qmd
        - semana9.qmd
        - semana10.qmd
        - semana11.qmd
        - semana12.qmd
        - semana13.qmd
      - section: "Readings"
        contents: 
        - Fabregas2013.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



