project:
  type: website
  output-dir: docs

website:
  title: "Spanish Morphology"
  sidebar:
    style: "docked"
    contents: 
      - text: "Home"
        href: index.qmd
      - section: "Syllabus"
        contents:
        - span431_syllabus.qmd
        - 431calendar.qmd
      - section: "Textbooks"
        contents:
        - Fabregas2013.qmd
        - bd1999.qmd
        - hualde2010.qmd
      - section: "Articles"
        contents: 
        - articles.qmd
      - section: "Semana 1"
        contents:
        - semana1.qmd
      - section: "Semana 2"
        contents: 
        - w1d2.qmd
        - handout3.qmd
        - handout4.qmd
      - section: "Semana 3"
        contents:
        - handout5.qmd
        - laderivacion.qmd
      - section: "Semana 4"
        contents: 
        - handout9.qmd
        - handout10.qmd
      - section: "Semana 5"
        contents: 
        - handout11.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



