---
title: "Articles"
---

## Semana 8 - Variation

- Gutiérrez-Rexach, J., & Sessarego, S. (2014). Morphosyntactic variation and gender agreement in three Afro-Andean dialects. Lingua, 151, 142-161.

- Navarro, Í., & Espinal, M. T. (2012). Le-predicates and event modification in Mexican Spanish. Lingua, 122(4), 409-431.

## Semana 9 - Child acquisition

- Clahsen, H., Aveledo, F., & Roca, I. (2002). The development of regular and irregular verb inflection in Spanish child language. Journal of child language, 29(3), 591-622.
    - Franco

- Mariscal, S. (2009). Early acquisition of gender agreement in the Spanish noun phrase: starting small. Journal of Child Language, 36(1), 143-171.
    - Kamila

## Semana 10 - Sociolinguistics

- Escobar, A. M., & Roy, J. (2022). Grammaticalization in the Evidential pathway of the Andean Spanish Present Perfect: Language contact as a trigger for language change. Isogloss, 8(4), 1-38.

- Barnes, S. (2012). ¿ Qué dijistes?: A variationist reanalysis of non-standard-s on second person singular preterit verb forms in Spanish. In Selected Proceedings of the 14th Hispanic Linguistics Symposium (pp. 38-47). Somerville, MA: Cascadilla Proceedings Project.
    - Alonso

- Escalante, C. (2015). ¿ Qué twiteastes tú? Variation in second person singular preterit–s in Spanish tweets. Entrehojas: Revista de Estudios Hispánicos, 5(1).

- Papadopoulos, B. (2024). Identifying Gender in Gendered Languages: The Case of Spanish. Redoing Linguistic Worlds: Unmaking Gender Binaries, Remaking Gender Pluralities, 30.

## Semana 11 - Heritage Speakers

- Montrul, S. (2010). Dominant language transfer in adult second language learners and heritage speakers. Second Language Research, 26(3), 293-327.
    - Edwin

- Scontras, G., Polinsky, M., & Fuchs, Z. (2018). In support of representational economy: Agreement in heritage Spanish. Glossa: A journal of general linguistics, 3(1).

- Foote, R. (2011). Integrated knowledge of agreement in early and late English–Spanish bilinguals. Applied Psycholinguistics, 32(1), 187-220.

- Domínguez, L., Arche, M. J., & Myles, F. (2017). Spanish Imperfect revisited: Exploring L1 influence in the reassembly of imperfective features onto new L2 forms. Second language research, 33(4), 431-457.

## Semana 12 - Distributed Morphology

- Embick, D., & Noyer, R. (2007). Distributed morphology and the syntax—morphology interface.

- Acquaviva, P. (2009). Roots and lexicality in Distributed Morphology. In Alexandra Galani, Daniel Redinger and Norman Yeo (eds.). YPL2-Issue 10 (May 2009) Special Issue-York-

- Smith, Peter (forth) DM and Minimalism. The Cambridge Handbook of Distributed Morphology

## Semana 13 - Code-switching and DM

- López, L. (forth). Distributed Morphology and Bilingualism: Code-switching and Mixed Languages. The Cambridge Handbook of Distributed Morphology

- López, L. (2020). Bilingual grammar: Toward an integrated model. Cambridge University Press.
    - Various chapters

