---
title: "Syllabus"
author:
  - "Delgado, FA24"
  - "TR 12:30 pm - 1:50 pm"
  - "316N Mumford Hall"
highlight-style: pygments
format:
  html: default
  pdf: default
  docx: default
---

**Professor**: Dr. Rodrigo Delgado

**Office**: 4135 Literatures, Cultures & Linguistics Building (LCLB)

**Office hours**: By appointment only

**email**: rdelga21\@illinois.edu

## Objectivos principales del curso

1. Introducir los fenómenos morfológicos del español, principalmente desde una perspectiva formal. 

2. Introducir las teorías de la morfología.

3. Explorar estudios de otras areas que se relacionan con la morfología.

## Materiales del curso

1.  Los PPT que se usaran en clase.

2.  Lecturas variadas que estarán disponibles en la página. Las lecturas estarán guardadas en la carpeta de la semana correspondiente. 


## La composición de la nota:

1. Tarea (6): **30%**
- Estas tareas se entregarán en Moodle
Cada dos semanas 

2. Presentación de artículo
- La presentación incluirá	una síntesis del estudio (fenómeno lingüístico, hipótesis, metodología de análisis y conclusión) con anotaciones críticas y dos preguntas finales de reflexión. Tendrá 1 hora para la presentación. 

3. Investigación final: **40%**
- Sobre un fenomeno morfológico del español.
- Incluye: 
    - Abstract del trabajo de 2 páginas (5%)
    - Análisis crítico de un artículo del trabajo final (10%)
        - El artículo escogido deber ser aprovado por el profesor
    - Presentación del trabajo final (10%)
    - El paper final de &pm;15 páginas, doble espacio (15%)
  
4. Asistencia: **5%**

5. Participación: **5%**
    
**Life happens clause** - You can invoke the clause on one deadline and get a 3-day extension. No explanation required. To use it, please email me stating that you are invoking the clause and the name of the assignment. Tests are excluded. 

